export const PDF_EXPORT_CONFIG = {
  // Document settings
  document: {
    title: 'LunaLens Landslide Detection Report',
    author: 'LunaLens AI System',
    subject: 'Lunar Surface Analysis Report',
    creator: 'LunaLens Landslide Detection System',
    producer: 'LunaLens PDF Generator'
  },
  
  // Page settings
  page: {
    margin: {
      top: 20,
      bottom: 20,
      left: 20,
      right: 20
    },
    size: 'A4'
  },
  
  // Colors
  colors: {
    primary: '#1f2937',
    secondary: '#374151',
    accent: '#3b82f6',
    success: '#10b981',
    warning: '#f59e0b',
    danger: '#ef4444',
    text: '#1f2937',
    textLight: '#6b7280',
    background: '#ffffff'
  },
  
  // Fonts
  fonts: {
    title: 'Helvetica-Bold',
    subtitle: 'Helvetica-Bold',
    body: 'Helvetica',
    table: 'Helvetica'
  },
  
  // Font sizes
  fontSize: {
    title: 24,
    subtitle: 18,
    section: 16,
    body: 12,
    table: 10,
    caption: 8
  },
  
  // Spacing
  spacing: {
    section: 20,
    paragraph: 10,
    table: 8,
    element: 5
  }
};

export const PDF_SECTIONS = {
  COVER_PAGE: 'cover_page',
  EXECUTIVE_SUMMARY: 'executive_summary',
  DETECTION_RESULTS: 'detection_results',
  DETAILED_ANALYSIS: 'detailed_analysis',
  TECHNICAL_DATA: 'technical_data',
  DENSITY_ANALYSIS: 'density_analysis',
  IMAGES: 'images',
  APPENDIX: 'appendix'
};

export const PDF_TEMPLATES = {
  coverPage: {
    title: 'LunaLens Landslide Detection Report',
    subtitle: 'Advanced AI-Powered Lunar Surface Analysis',
    logo: '🌙',
    dateFormat: 'MMMM DD, YYYY',
    footer: 'Generated by LunaLens AI System'
  },
  
  executiveSummary: {
    title: 'Executive Summary',
    sections: [
      'Analysis Overview',
      'Key Findings',
      'Detection Statistics',
      'Recommendations'
    ]
  },
  
  detectionResults: {
    title: 'Detection Results',
    tableHeaders: [
      'Object',
      'Type',
      'Confidence',
      'Diameter (m)',
      'Area (m²)',
      'Volume (m³)',
      'Circularity'
    ]
  },
  
  technicalData: {
    title: 'Technical Data',
    sections: [
      'Bounding Boxes',
      'Pixel Measurements',
      'Shape Properties',
      'Processing Information'
    ]
  }
};

export const PDF_STYLES = {
  header: {
    fontSize: 24,
    font: 'Helvetica-Bold',
    color: '#1f2937',
    alignment: 'center'
  },
  
  subheader: {
    fontSize: 18,
    font: 'Helvetica-Bold',
    color: '#374151',
    alignment: 'left'
  },
  
  section: {
    fontSize: 16,
    font: 'Helvetica-Bold',
    color: '#3b82f6',
    alignment: 'left'
  },
  
  body: {
    fontSize: 12,
    font: 'Helvetica',
    color: '#1f2937',
    alignment: 'left'
  },
  
  table: {
    fontSize: 10,
    font: 'Helvetica',
    color: '#1f2937',
    alignment: 'left',
    headerColor: '#f3f4f6',
    borderColor: '#d1d5db'
  },
  
  caption: {
    fontSize: 8,
    font: 'Helvetica',
    color: '#6b7280',
    alignment: 'center'
  }
};

export const PDF_LAYOUTS = {
  coverPage: {
    logoSize: 80,
    titleSpacing: 30,
    subtitleSpacing: 20,
    footerSpacing: 40
  },
  
  table: {
    headerHeight: 25,
    rowHeight: 20,
    cellPadding: 5,
    borderWidth: 1
  },
  
  image: {
    maxWidth: 400,
    maxHeight: 300,
    captionSpacing: 5
  }
}; 
